# Logger
exp_name: cheetah
record_interval: 1

# Environment
task: visual_franka_slide_random-v3
frame_skip: 2
from_pixels: true
reward_scaling: 5.0
init_env_steps: 1000
seed: 42

# Collector
env_per_collector: 1
total_frames: 1000000
init_random_frames: 25000
frames_per_batch: 1000

# Replay Buffer
prb: 0
buffer_size: 100000

# Optimization
gamma: 0.99
batch_size: 256
lr: 3.0e-4
weight_decay: 0.0
target_update_polyak: 0.995
